### ISSUE TITLE
#5: Correct .gitignore file

### ISSUE THREAD

**Issue by ghost** [vitodevjav/qulix#8]
Please, remove unneeded lines from .gitignore file and add/correct some lines to ignore user's data.
Remove ignored files from `git` index

**Comment by vitodevjav** [comment]
check it first, pls

**Comment by vitodevjav** [comment]
issue5 (it seems to be fixed)

**Comment by vitodevjav** [comment]
ready

**Comment by ghost** [comment]
@vitodevjav Еще ж не пофикшено, почему закрываешь (еще и сам)?

**Comment by vitodevjav** [comment]
что не пофикшено?

**Comment by vitodevjav** [comment]
мона удалять

**Comment by ghost** [comment]
Thanks!
